In [1]:
# pip install numpy (jupyter)
import numpy as np

In [2]:
age = np.array([25,24,26,23,24]) # Row vector
age

array([25, 24, 26, 23, 24])

# Numpy attribute

In [3]:
age

array([25, 24, 26, 23, 24])

In [4]:
# n.dim : it will give the dimension of the array
age.ndim

1

In [5]:
# n.shape : It is a tuple which returns the number of elements per axis
age.shape

(5,)

In [6]:
# n.size : It counts the number of elements
age.size

5

In [7]:
# n.dtype : it returns the datatype
age.dtype

dtype('int64')

In [8]:
age = np.array([[25],[24],[26],[23],[24]]) # Column vector
age

array([[25],
       [24],
       [26],
       [23],
       [24]])

In [9]:
age.ndim

2

In [10]:
age.shape

(5, 1)

In [11]:
age.size

5

In [12]:
data = np.array([[25,160,50],[24,162,45],[26,165,70],[23,158,48],[24,162,52]]) # Column vector
data

array([[ 25, 160,  50],
       [ 24, 162,  45],
       [ 26, 165,  70],
       [ 23, 158,  48],
       [ 24, 162,  52]])

In [13]:
data.ndim

2

In [14]:
data.shape # number of rows and columns

(5, 3)

In [15]:
data.size

15

In [16]:
d1 = data[:,0:1]
d1

array([[25],
       [24],
       [26],
       [23],
       [24]])

In [17]:
d2 = data[:,0:2]
d2

array([[ 25, 160],
       [ 24, 162],
       [ 26, 165],
       [ 23, 158],
       [ 24, 162]])

# Statistical operation

In [18]:
d1

array([[25],
       [24],
       [26],
       [23],
       [24]])

In [20]:
print("Mean :",np.mean(d1))
print("Median :",np.median(d1))
print("Mode :",np.mode(d1))

Mean : 24.4
Median : 24.0

AttributeError: module 'numpy' has no attribute 'mode'

In [21]:
print("Min: ",np.min(d1))
print("Max: ",np.max(d1))

Min:  23
Max:  26

In [22]:
print("Standard Deviation: ",np.std(d1))
print("Variance: ",np.var(d1))

Standard Deviation:  1.019803902718557
Variance:  1.04

In [25]:
data

array([[ 25, 160,  50],
       [ 24, 162,  45],
       [ 26, 165,  70],
       [ 23, 158,  48],
       [ 24, 162,  52]])

In [26]:
data + 10

array([[ 35, 170,  60],
       [ 34, 172,  55],
       [ 36, 175,  80],
       [ 33, 168,  58],
       [ 34, 172,  62]])

# Numpy Arithmetic

In [23]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b = np.array([[10,20,30],[1,2,3],[4,4,4]])
b

array([[10, 20, 30],
       [ 1,  2,  3],
       [ 4,  4,  4]])

In [28]:
np.add(a,b) # a + b

array([[11, 22, 33],
       [ 5,  7,  9],
       [11, 12, 13]])

In [29]:
np.subtract(a,b) # a - b

array([[ -9, -18, -27],
       [  3,   3,   3],
       [  3,   4,   5]])

In [30]:
np.multiply (a,b) # a * b

array([[10, 40, 90],
       [ 4, 10, 18],
       [28, 32, 36]])

In [31]:
np.divide(a,b) # a / b

array([[0.1 , 0.1 , 0.1 ],
       [4.  , 2.5 , 2.  ],
       [1.75, 2.  , 2.25]])

In [32]:
a // b # returns only integer value

array([[0, 0, 0],
       [4, 2, 2],
       [1, 2, 2]])

In [33]:
np.mod(a,b) # a % b

array([[1, 2, 3],
       [0, 1, 0],
       [3, 0, 1]])

In [34]:
np.remainder(a,b) # a % b

array([[1, 2, 3],
       [0, 1, 0],
       [3, 0, 1]])

In [39]:
np.random.random(10) # it will print 10 values between 0 and 1

array([0.86905595, 0.78234678, 0.53066573, 0.57437968, 0.57678232,
       0.65121808, 0.11883897, 0.38205687, 0.89802294, 0.80255364])

In [55]:
a1 = np.random.randint(10) # print between 0 to 9
a1

0

In [58]:
a2 = np.random.randint(10, size = 7) # print between 0 to 9
a2

array([0, 0, 6, 8, 8, 0, 5])

In [59]:
a2.ndim

1

In [60]:
a3 = np.random.randint(10, size = (2,3)) # print between 0 to 9
a3

array([[0, 7, 7],
       [9, 8, 4]])

In [61]:
a3 = np.random.randint(10, size = (3,2)) # print between 0 to 9
a3

array([[1, 3],
       [7, 4],
       [0, 2]])

In [62]:
a3.ndim

2

In [65]:
a4 = np.random.randint(10, size = (3,2,3)) # print between 0 to 9
a4

array([[[6, 4, 4],
        [6, 6, 0]],

       [[3, 0, 6],
        [6, 0, 9]],

       [[0, 1, 3],
        [2, 7, 7]]])

In [64]:
a4.ndim

3

In [66]:
data

array([[ 25, 160,  50],
       [ 24, 162,  45],
       [ 26, 165,  70],
       [ 23, 158,  48],
       [ 24, 162,  52]])

In [67]:
# pip install pandas (jupyter)
import pandas as pd

In [68]:
data = pd.DataFrame(data)
data

    0    1   2
0  25  160  50
1  24  162  45
2  26  165  70
3  23  158  48
4  24  162  52

In [69]:
data.columns = ["Age","Height","Weight"]
data

   Age  Height  Weight
0   25     160      50
1   24     162      45
2   26     165      70
3   23     158      48
4   24     162      52

# pandas Statistical Operations

In [70]:
print("Mean: ",data.mean())
print("Median: ",data.median())
print("Mode: ",data.mode())

Mean:  Age        24.4
Height    161.4
Weight     53.0
dtype: float64
Median:  Age        24.0
Height    162.0
Weight     50.0
dtype: float64
Mode:      Age  Height  Weight
0  24.0   162.0      45
1   NaN     NaN      48
2   NaN     NaN      50
3   NaN     NaN      52
4   NaN     NaN      70

In [72]:
d1 = data["Weight"]
d1

0    50
1    45
2    70
3    48
4    52
Name: Weight, dtype: int64

In [75]:
d1 + 10

0    60
1    55
2    80
3    58
4    62
Name: Weight, dtype: int64

In [76]:
print("Mean :",d1.mean())
print("Median :",d1.median())
print("Mode :",d1.mode())
print("Min :",d1.min())
print("Max :",d1.max())
print("Standard Deviation :",d1.std())
print("Variance :",d1.var())

Mean : 53.0
Median : 50.0
Mode : 0    45
1    48
2    50
3    52
4    70
Name: Weight, dtype: int64
Min : 45
Max : 70
Standard Deviation : 9.848857801796104
Variance : 97.0