In [1]:
# import all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# read dataset
df1 = pd.read_csv('/content/first_file (2).csv')
df2 = pd.read_csv('/content/second_file (2).csv')
df3 = pd.read_csv('/content/third_file (2).csv')

In [3]:
# EDA
df1

    id   age  height  weight
0  101  24.0     175      85
1  102  25.0     165      75
2  103  30.0     168      72
3  104   NaN     172      78
4  105  28.0     170      76

In [4]:
df1["age"].fillna(df1["age"].mean(), inplace = True)
df1

/tmp/ipykernel_4065/3621456303.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["age"].fillna(df1["age"].mean(), inplace = True)

    id    age  height  weight
0  101  24.00     175      85
1  102  25.00     165      75
2  103  30.00     168      72
3  104  26.75     172      78
4  105  28.00     170      76

In [5]:
df2

    id  age  height  weight
0  106   28     174      68
1  107   32     168      76
2  108   37     158      73
3  109   40     176      80
4  110   30     169      85

In [6]:
df4 = pd.concat([df1,df2])
df4

    id    age  height  weight
0  101  24.00     175      85
1  102  25.00     165      75
2  103  30.00     168      72
3  104  26.75     172      78
4  105  28.00     170      76
0  106  28.00     174      68
1  107  32.00     168      76
2  108  37.00     158      73
3  109  40.00     176      80
4  110  30.00     169      85

In [7]:
df4 = pd.concat([df1,df2], ignore_index= True)
df4

    id    age  height  weight
0  101  24.00     175      85
1  102  25.00     165      75
2  103  30.00     168      72
3  104  26.75     172      78
4  105  28.00     170      76
5  106  28.00     174      68
6  107  32.00     168      76
7  108  37.00     158      73
8  109  40.00     176      80
9  110  30.00     169      85

In [8]:
df3

  Gender   BP
0      M  120
1      F  140
2      M  145
3      F  132
4      M  130
5      F  150
6      M  147
7      F  132
8      F  128
9      F  130

In [9]:
df5= pd.concat([df4,df3])
df5

      id    age  height  weight Gender     BP
0  101.0  24.00   175.0    85.0    NaN    NaN
1  102.0  25.00   165.0    75.0    NaN    NaN
2  103.0  30.00   168.0    72.0    NaN    NaN
3  104.0  26.75   172.0    78.0    NaN    NaN
4  105.0  28.00   170.0    76.0    NaN    NaN
5  106.0  28.00   174.0    68.0    NaN    NaN
6  107.0  32.00   168.0    76.0    NaN    NaN
7  108.0  37.00   158.0    73.0    NaN    NaN
8  109.0  40.00   176.0    80.0    NaN    NaN
9  110.0  30.00   169.0    85.0    NaN    NaN
0    NaN    NaN     NaN     NaN      M  120.0
1    NaN    NaN     NaN     NaN      F  140.0
2    NaN    NaN     NaN     NaN      M  145.0
3    NaN    NaN     NaN     NaN      F  132.0
4    NaN    NaN     NaN     NaN      M  130.0
5    NaN    NaN     NaN     NaN      F  150.0
6    NaN    NaN     NaN     NaN      M  147.0
7    NaN    NaN     NaN     NaN      F  132.0
8    NaN    NaN     NaN     NaN      F  128.0
9    NaN    NaN     NaN     NaN      F  130.0

In [10]:
df5= pd.concat([df4,df3], axis =1)
df5

    id    age  height  weight Gender   BP
0  101  24.00     175      85      M  120
1  102  25.00     165      75      F  140
2  103  30.00     168      72      M  145
3  104  26.75     172      78      F  132
4  105  28.00     170      76      M  130
5  106  28.00     174      68      F  150
6  107  32.00     168      76      M  147
7  108  37.00     158      73      F  132
8  109  40.00     176      80      F  128
9  110  30.00     169      85      F  130

In [11]:
df5["age"] = df5["age"].astype("int")
df5

    id  age  height  weight Gender   BP
0  101   24     175      85      M  120
1  102   25     165      75      F  140
2  103   30     168      72      M  145
3  104   26     172      78      F  132
4  105   28     170      76      M  130
5  106   28     174      68      F  150
6  107   32     168      76      M  147
7  108   37     158      73      F  132
8  109   40     176      80      F  128
9  110   30     169      85      F  130

In [15]:
a = 32.45
print(type(a))
print(np.round(a))
print(type(a))

<class 'float'>
32.0
<class 'float'>